sudo: false
language: ruby
rvm:
  - 2.3.1
before_install:
  - gem install rubocop -v 0.40.0
script:
  - rubocop .
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake test:units
  - bundle exec rake test:functionals
